# Configuration for Alacritty, the GPU enhanced terminal emulator.

#env:
window:
  padding:
    x: 26
    y: 20
  dynamic_padding: true
  opacity: 1

scrolling:
  history: 5000

font:
  normal:
    family: "TerminessTTF Nerd Font" 
    style: "Regular"
  bold:
    family: "TerminessTTF Nerd Font"
    style: "Bold"
  italic:
    family: "TerminessTFF Nerd Font"
    style: "Italics"
  bold_italic:
    family: "TerminessTTF Nerd Font"
    style: "Regular"
  size: 18

live_config_reload: true

colors:
  primary:
    background: "0x1d2021"
    foreground: "0x8ec07c"

  normal:
    black: "0x665c54"
    red: "0xea6962"
    green: "0xa9b665"
    yellow: "0xe78a4e"
    blue: "0x7daea3"
    magenta: "0xd3869b"
    cyan: "0x89b482"
    white: "0xdfbf8e"

  bright:
    black: "0x928374"
    red: "0xea6962"
    green: "0xa9b665"
    yellow: "0xe3a84e"
    blue: "0x7daea3"
    magenta: "0xd3869b"
    cyan: "0x89b482"
    white: "0xdfbf8e"

cursor:
  style:
    shape: Underline
  vi_mode_cursor:
    text: CellBackground
    cursor: Underline
